name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test-go:
    name: Test Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./...

      - name: Run go vet
        run: go vet ./...

      - name: Build
        run: go build -v ./cmd/devgru

  test-extension:
    name: Test VS Code Extension
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "vscode-extension/package-lock.json"

      - name: Install dependencies
        run: |
          npm install
          cd vscode-extension && npm install

      - name: Compile TypeScript
        run: cd vscode-extension && npm run compile

      - name: Run tests
        run: cd vscode-extension && npm test

  build:
    name: Build Release Artifacts
    runs-on: ubuntu-latest
    needs: [test-go, test-extension]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: make install

      - name: Build Go binary
        run: make build-go

      - name: Package VS Code extension
        run: make package-extension

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: devgru-artifacts
          path: |
            bin/devgru
            vscode-extension/*.vsix
